# Site settings
title: Toby Sullivan Codes
email: tobyjsullivan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A software developer in Vancouver shares his thoughts - as few and 
  inconsistent as they are.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tobyjsullivan.github.io" # the base hostname & protocol for your site
twitter_username: tobyjsullivan
github_username:  tobyjsullivan

# Build settings
markdown: kramdown
